In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/1000-instances/1000_instances_to_translate.csv

In [ ]:
x='''চিফ কমপ্লেইন্ট: অস্বাভাবিক ইটিটি, ইলেকটিভ কার্ডিয়াক ক্যাথেটারাইজেশনের জন্য রেফার্ড।
বর্তমান অসুস্থতা: মি. [পরিচিত শেষ নাম ১৯৬৮] ৬৩ বছর বয়সী পুরুষ, যার অ্যাবডোমিনাল অ্যাওর্টিক অ্যানিউরিজম রয়েছে যা ডানদিকের হিপের অস্বস্তির মূল্যায়নের সময় ঘটনাক্রমে পাওয়া গেছে। অ্যাবডোমিনাল অ্যাওর্টিক অ্যানিউরিজমের প্রি-অপারেটিভ মূল্যায়নে [২১৯৩-৬-৭]-এ পারসান্টাইন ইটিটি করা হয়, যেখানে মাঝারি বেসিলার এবং মিড ইনফেরিয়র ওয়ালে রিভার্সিবল ডিফেক্ট পাওয়া যায়। তার এলভিইএফ ৫২% হিসেবে অনুমান করা হয়। এরপর তাকে ইলেকটিভ কার্ডিয়াক ক্যাথেটারাইজেশনের জন্য রেফার করা হয়। তিনি কোনো বুকে অস্বস্তি বা শ্বাসকষ্টের ইতিহাস অস্বীকার করেন। তিনি ক্লডিকেশন, পিএনডি, অরথোপনিয়া, পেডাল ইডিমা, সিঙ্কোপ এবং প্রিসিঙ্কোপের কথাও অস্বীকার করেন।

মেডিক্যাল ইতিহাস: এএএ, এইচটিএন, জিইআরডি, বিপিএইচ, উচ্চ কোলেস্টেরল, স্থূলতা, হিপের অস্বস্তি, এস/পি মেলানোমা অপসারণ।

ভর্তির সময়ের ওষুধ:

বাসপার ১৫ [হাসপাতাল১],
ফ্লেক্সেরিল ১০ প্রি.এন.,
ফ্লোম্যাক্স ০.৪ [হাসপাতাল১],
লোভাস্টাটিন ৪০ কিউ.ডি.,
নেক্সিয়াম ৪০ কিউ.ডি.,
টোপ্রল এক্সএল ২৫ [হাসপাতাল১],
ডিট্রোপ্যান ৫ [হাসপাতাল১],
অ্যাসপিরিন ৮১ কিউ.ডি.,
ভিটামিন সি,
এমভিআই।
অ্যালার্জি: ওষুধ সংক্রান্ত কোনো অ্যালার্জির তথ্য নেই।

শারীরিক পরীক্ষা:

রক্তচাপ: ১৩০-১৪০/৭০-৮০
নাড়ির গতি: ৬০-এর ঘরে
শ্বাসপ্রশ্বাস: ১৮ (রুম এয়ার-এ ১০০% স্যাচুরেশন)
সাধারণ: কোনো তীব্র সমস্যায় নেই, সদয় চেহারা
ওরোফ্যারিংক্স: স্বাভাবিক
ঘাড়: নরম, কোনো জেভিডি নেই, ক্যারোটিড ব্রুইট নেই
ফুসফুস: শ্রবণে পরিষ্কার
হার্ট: স্বাভাবিক হার ও ছন্দ, স্বাভাবিক s1s2, কোনো মর্মর বা রাব নেই
পেট: স্থূল, নরম, ব্যথাহীন, অপ্রসারিত
অঙ্গ-প্রত্যঙ্গ: উষ্ণ, ইডিমা নেই
ডিস্টাল পালস: উভয় দিকে ১+, কোনো ফেমোরাল ব্রুইট নেই
নিউরো: সচেতন এবং সচেতন, সিএন ২-১২ মোটামুটি অক্ষত, কোনো ফোকাল ঘাটতি নেই।
পারিবারিক ইতিহাস:

বাবা ৬৫ বছর বয়সে হার্ট অ্যাটাক করেছিলেন এবং পরবর্তীতে সিএবিজি করান।
মা-ও তার ৬০-এর দশকে হার্ট অ্যাটাক করেছিলেন।
সামাজিক ইতিহাস:

৭ বছর আগে তামাক ছেড়েছেন। দীর্ঘদিন ধরে প্রতিদিন ২ প্যাকেট ধূমপানের অভ্যাস ছিল।
অতিরিক্ত অ্যালকোহল সেবনের কথা অস্বীকার করেন।
তিনি বিবাহিত এবং তার দুই প্রাপ্তবয়স্ক সন্তান রয়েছে।'''

In [ ]:
x

'চিফ কমপ্লেইন্ট: অস্বাভাবিক ইটিটি, ইলেকটিভ কার্ডিয়াক ক্যাথেটারাইজেশনের জন্য রেফার্ড।\nবর্তমান অসুস্থতা: মি. [পরিচিত শেষ নাম ১৯৬৮] ৬৩ বছর বয়সী পুরুষ, যার অ্যাবডোমিনাল অ্যাওর্টিক অ্যানিউরিজম রয়েছে যা ডানদিকের হিপের অস্বস্তির মূল্যায়নের সময় ঘটনাক্রমে পাওয়া গেছে। অ্যাবডোমিনাল অ্যাওর্টিক অ্যানিউরিজমের প্রি-অপারেটিভ মূল্যায়নে [২১৯৩-৬-৭]-এ পারসান্টাইন ইটিটি করা হয়, যেখানে মাঝারি বেসিলার এবং মিড ইনফেরিয়র ওয়ালে রিভার্সিবল ডিফেক্ট পাওয়া যায়। তার এলভিইএফ ৫২% হিসেবে অনুমান করা হয়। এরপর তাকে ইলেকটিভ কার্ডিয়াক ক্যাথেটারাইজেশনের জন্য রেফার করা হয়। তিনি কোনো বুকে অস্বস্তি বা শ্বাসকষ্টের ইতিহাস অস্বীকার করেন। তিনি ক্লডিকেশন, পিএনডি, অরথোপনিয়া, পেডাল ইডিমা, সিঙ্কোপ এবং প্রিসিঙ্কোপের কথাও অস্বীকার করেন।\n\nমেডিক্যাল ইতিহাস: এএএ, এইচটিএন, জিইআরডি, বিপিএইচ, উচ্চ কোলেস্টেরল, স্থূলতা, হিপের অস্বস্তি, এস/পি মেলানোমা অপসারণ।\n\nভর্তির সময়ের ওষুধ:\n\nবাসপার ১৫ [হাসপাতাল১],\nফ্লেক্সেরিল ১০ প্রি.এন.,\nফ্লোম্যাক্স ০.৪ [হাসপাতাল১],\nলোভাস্টাটিন ৪০ কিউ.ডি.,\nনেক্সিয়াম ৪০ কিউ.ডি.,\nটোপ্রল এক্সএল ২৫ [হাসপাতাল১],\nডিট্রোপ্যান ৫ [হাসপাতাল১],\nঅ্যাসপিরিন ৮১ কিউ.ডি.,\nভিটামিন সি,\nএমভিআই।\nঅ্যালার্জি: ওষুধ সংক্রান্ত কোনো অ্যালার্জির তথ্য নেই।\n\nশারীরিক পরীক্ষা:\n\nরক্তচাপ: ১৩০-১৪০/৭০-৮০\nনাড়ির গতি: ৬০-এর ঘরে\nশ্বাসপ্রশ্বাস: ১৮ (রুম এয়ার-এ ১০০% স্যাচুরেশন)\nসাধারণ: কোনো তীব্র সমস্যায় নেই, সদয় চেহারা\nওরোফ্যারিংক্স: স্বাভাবিক\nঘাড়: নরম, কোনো জেভিডি নেই, ক্যারোটিড ব্রুইট নেই\nফুসফুস: শ্রবণে পরিষ্কার\nহার্ট: স্বাভাবিক হার ও ছন্দ, স্বাভাবিক s1s2, কোনো মর্মর বা রাব নেই\nপেট: স্থূল, নরম, ব্যথাহীন, অপ্রসারিত\nঅঙ্গ-প্রত্যঙ্গ: উষ্ণ, ইডিমা নেই\nডিস্টাল পালস: উভয় দিকে ১+, কোনো ফেমোরাল ব্রুইট নেই\nনিউরো: সচেতন এবং সচেতন, সিএন ২-১২ মোটামুটি অক্ষত, কোনো ফোকাল ঘাটতি নেই।\nপারিবারিক ইতিহাস:\n\nবাবা ৬৫ বছর বয়সে হার্ট অ্যাটাক করেছিলেন এবং পরবর্তীতে সিএবিজি করান।\nমা-ও তার ৬০-এর দশকে হার্ট অ্যাটাক করেছিলেন।\nসামাজিক ইতিহাস:\n\n৭ বছর আগে তামাক ছেড়েছেন। দীর্ঘদিন ধরে প্রতিদিন ২ প্যাকেট ধূমপানের অভ্যাস ছিল।\nঅতিরিক্ত অ্যালকোহল সেবনের কথা অস্বীকার করেন।\nতিনি বিবাহিত এবং তার দুই প্রাপ্তবয়স্ক সন্তান রয়েছে।'

In [ ]:
x.replace('\n',' ')

'চিফ কমপ্লেইন্ট: অস্বাভাবিক ইটিটি, ইলেকটিভ কার্ডিয়াক ক্যাথেটারাইজেশনের জন্য রেফার্ড। বর্তমান অসুস্থতা: মি. [পরিচিত শেষ নাম ১৯৬৮] ৬৩ বছর বয়সী পুরুষ, যার অ্যাবডোমিনাল অ্যাওর্টিক অ্যানিউরিজম রয়েছে যা ডানদিকের হিপের অস্বস্তির মূল্যায়নের সময় ঘটনাক্রমে পাওয়া গেছে। অ্যাবডোমিনাল অ্যাওর্টিক অ্যানিউরিজমের প্রি-অপারেটিভ মূল্যায়নে [২১৯৩-৬-৭]-এ পারসান্টাইন ইটিটি করা হয়, যেখানে মাঝারি বেসিলার এবং মিড ইনফেরিয়র ওয়ালে রিভার্সিবল ডিফেক্ট পাওয়া যায়। তার এলভিইএফ ৫২% হিসেবে অনুমান করা হয়। এরপর তাকে ইলেকটিভ কার্ডিয়াক ক্যাথেটারাইজেশনের জন্য রেফার করা হয়। তিনি কোনো বুকে অস্বস্তি বা শ্বাসকষ্টের ইতিহাস অস্বীকার করেন। তিনি ক্লডিকেশন, পিএনডি, অরথোপনিয়া, পেডাল ইডিমা, সিঙ্কোপ এবং প্রিসিঙ্কোপের কথাও অস্বীকার করেন।  মেডিক্যাল ইতিহাস: এএএ, এইচটিএন, জিইআরডি, বিপিএইচ, উচ্চ কোলেস্টেরল, স্থূলতা, হিপের অস্বস্তি, এস/পি মেলানোমা অপসারণ।  ভর্তির সময়ের ওষুধ:  বাসপার ১৫ [হাসপাতাল১], ফ্লেক্সেরিল ১০ প্রি.এন., ফ্লোম্যাক্স ০.৪ [হাসপাতাল১], লোভাস্টাটিন ৪০ কিউ.ডি., নেক্সিয়াম ৪০ কিউ.ডি., টোপ্রল এক্সএল ২৫ [হাসপাতাল১], ডিট্রোপ্যান ৫ [হাসপাতাল১], অ্যাসপিরিন ৮১ কিউ.ডি., ভিটামিন সি, এমভিআই। অ্যালার্জি: ওষুধ সংক্রান্ত কোনো অ্যালার্জির তথ্য নেই।  শারীরিক পরীক্ষা:  রক্তচাপ: ১৩০-১৪০/৭০-৮০ নাড়ির গতি: ৬০-এর ঘরে শ্বাসপ্রশ্বাস: ১৮ (রুম এয়ার-এ ১০০% স্যাচুরেশন) সাধারণ: কোনো তীব্র সমস্যায় নেই, সদয় চেহারা ওরোফ্যারিংক্স: স্বাভাবিক ঘাড়: নরম, কোনো জেভিডি নেই, ক্যারোটিড ব্রুইট নেই ফুসফুস: শ্রবণে পরিষ্কার হার্ট: স্বাভাবিক হার ও ছন্দ, স্বাভাবিক s1s2, কোনো মর্মর বা রাব নেই পেট: স্থূল, নরম, ব্যথাহীন, অপ্রসারিত অঙ্গ-প্রত্যঙ্গ: উষ্ণ, ইডিমা নেই ডিস্টাল পালস: উভয় দিকে ১+, কোনো ফেমোরাল ব্রুইট নেই নিউরো: সচেতন এবং সচেতন, সিএন ২-১২ মোটামুটি অক্ষত, কোনো ফোকাল ঘাটতি নেই। পারিবারিক ইতিহাস:  বাবা ৬৫ বছর বয়সে হার্ট অ্যাটাক করেছিলেন এবং পরবর্তীতে সিএবিজি করান। মা-ও তার ৬০-এর দশকে হার্ট অ্যাটাক করেছিলেন। সামাজিক ইতিহাস:  ৭ বছর আগে তামাক ছেড়েছেন। দীর্ঘদিন ধরে প্রতিদিন ২ প্যাকেট ধূমপানের অভ্যাস ছিল। অতিরিক্ত অ্যালকোহল সেবনের কথা অস্বীকার করেন। তিনি বিবাহিত এবং তার দুই প্রাপ্তবয়স্ক সন্তান রয়েছে।'

In [ ]:
all

      Unnamed: 0                                               text  los_label
0              0  CHIEF COMPLAINT: [**Last Name (un) **]\n\nPRES...          2
1              1  CHIEF COMPLAINT: Fevers\n\nPRESENT ILLNESS: In...          0
2              2  CHIEF COMPLAINT: ETOH intoxication and diarrhe...          1
3              3  CHIEF COMPLAINT: "hypotension."\n\nPRESENT ILL...          0
4              4  CHIEF COMPLAINT: Syncope\n\nPRESENT ILLNESS: 6...          0
...          ...                                                ...        ...
996          996  CHIEF COMPLAINT: (positive blood cultures)\n\n...          1
997          997  CHIEF COMPLAINT: visual disturbance, left side...          2
998          998  CHIEF COMPLAINT: \n\nPRESENT ILLNESS: Mr. [**K...          2
999          999  CHIEF COMPLAINT: CHIEF COMPLAINT:  chest pain ...          0
1000        1000  CHIEF COMPLAINT: fever\n\nPRESENT ILLNESS: The...          3

[1001 rows x 3 columns]

In [ ]:
all=pd.read_csv('/kaggle/input/1000-instances/1000_instances_to_translate.csv',usecols=['text','los_label'])

In [ ]:
all

                                                   text  los_label
0     CHIEF COMPLAINT: [**Last Name (un) **]\n\nPRES...          2
1     CHIEF COMPLAINT: Fevers\n\nPRESENT ILLNESS: In...          0
2     CHIEF COMPLAINT: ETOH intoxication and diarrhe...          1
3     CHIEF COMPLAINT: "hypotension."\n\nPRESENT ILL...          0
4     CHIEF COMPLAINT: Syncope\n\nPRESENT ILLNESS: 6...          0
...                                                 ...        ...
996   CHIEF COMPLAINT: (positive blood cultures)\n\n...          1
997   CHIEF COMPLAINT: visual disturbance, left side...          2
998   CHIEF COMPLAINT: \n\nPRESENT ILLNESS: Mr. [**K...          2
999   CHIEF COMPLAINT: CHIEF COMPLAINT:  chest pain ...          0
1000  CHIEF COMPLAINT: fever\n\nPRESENT ILLNESS: The...          3

[1001 rows x 2 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    all, all['los_label'], test_size=0.2, random_state=0,stratify=all['los_label'])

In [ ]:
len(x_train) , len(x_test)

(800, 201)

In [ ]:
x_train.los_label.value_counts(normalize=True)*100

los_label
1    36.875
2    30.625
3    19.625
0    12.875
Name: proportion, dtype: float64

In [ ]:
x_val, x_testi, y_val, y_testi = train_test_split(
    x_test, x_test['los_label'], test_size=0.5, random_state=0,stratify=x_test['los_label'])

In [ ]:
print(x_val.los_label.value_counts(normalize=True)*100,end="\n \n")
print(x_testi.los_label.value_counts(normalize=True)*100)

los_label
1    37.0
2    31.0
3    19.0
0    13.0
Name: proportion, dtype: float64

los_label
1    36.633663
2    30.693069
3    19.801980
0    12.871287
Name: proportion, dtype: float64

In [ ]:
len(x_val) , len(x_testi)

(100, 101)

In [ ]:
x_train.to_excel('Prompt Train 800.xlsx')
x_val.to_excel('Prompt Val 100.xlsx')
x_testi.to_excel('Prompt Test 101.xlsx')

In [ ]:
x_train[:340].to_excel('Sayed Bhai Train 0-340.xlsx')
x_train[340:680].to_excel('Monmoy Bhai Train 340-680.xlsx')
x_train[680:].to_excel('Rakib Train 680-~.xlsx')

In [ ]:
x_train[680:]

                                                  text  los_label
209  CHIEF COMPLAINT: Suboccipital Crani for Mass\n...          3
636  CHIEF COMPLAINT: \n\nPRESENT ILLNESS: The pati...          3
537  CHIEF COMPLAINT: OSH Transfer\n\nPRESENT ILLNE...          3
424  CHIEF COMPLAINT: Multiple cervical and thoraci...          3
98   CHIEF COMPLAINT: R iliac vein bleeding\n\nPRES...          3
..                                                 ...        ...
493  CHIEF COMPLAINT: bright red blood per rectum\n...          1
673  CHIEF COMPLAINT: Sternal drainage\n\nPRESENT I...          2
16   CHIEF COMPLAINT: Admitted for TIPS\n\nPRESENT ...          1
344  CHIEF COMPLAINT: Status-post MVC with polytrau...          2
102  CHIEF COMPLAINT: Bloody diarrhea\n\nPRESENT IL...          2

[120 rows x 2 columns]

In [ ]:
x_train[340:680].to_excel('Monmoy Bhai Train 340-680.xlsx')